name: Test Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npm run lint
